[package]
name = "cavegen_bot"
version = "0.1.0"
authors = ["mayabyte <mayahayden@protonmail.com>"]
edition = "2018"

[dependencies.serenity]
version = "0.10"
features = ["framework", "standard_framework", "rustls_backend"]

[dependencies.tokio]
version = "1.4"
features = ["macros", "rt-multi-thread", "process"]

[dependencies]
maplit = "1.0"
lazy_static = "1.4"
regex = "1.4"